require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const connectDB = require("../config/db");

const Category = require("../models/category");
const Seller = require("../models/sellersModel");
const Product = require("../models/productModel");

// ─── Helpers ──────────────────────────────────────────────────────────────────
const slug = (str) =>
  str.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

// ─── Seed Data ─────────────────────────────────────────────────────────────────
const CATEGORIES = [
  { name: "Electronics",     slug: "electronics",      description: "Gadgets, devices and accessories" },
  { name: "Fashion",         slug: "fashion",           description: "Clothing, footwear and accessories" },
  { name: "Home & Kitchen",  slug: "home-kitchen",      description: "Home decor, appliances and kitchen essentials" },
  { name: "Sports & Fitness",slug: "sports-fitness",    description: "Sportswear, equipment and fitness gear" },
  { name: "Books",           slug: "books",             description: "Fiction, non-fiction and educational books" },
];

const SELLER = {
  firstName: "Demo",
  lastName: "Seller",
  email: "demoseller@hellomem.com",
  phone: "9999900001",
  businessName: "HelloMem Store",
  businessType: "Company",
  gstNumber: "27AAPFU0939F1ZV",
  panNumber: "AAPFU0939F",
  address: { street: "12, MG Road", city: "Bangalore", state: "Karnataka", country: "India", pincode: "560001" },
  verificationStatus: "Approved",
  isVerified: true,
  isActive: true,
};

// ─── Products (30 items across 5 categories) ──────────────────────────────────
const buildProducts = (catMap, sellerId) => [
  // ── Electronics (6) ──────────────────────────────────────────────────────────
  {
    name: "Sony WH-1000XM5 Wireless Headphones",
    slug: "sony-wh-1000xm5-wireless-headphones",
    description: "Industry-leading noise canceling headphones with 30-hour battery life, multipoint connection and crystal-clear call quality.",
    shortDescription: "Premium noise-canceling wireless headphones",
    category: catMap["electronics"], brand: "Sony", seller: sellerId,
    price: 24990, discountPrice: 21990, mrp: 29990, costPrice: 15000, gst: 18,
    taxType: "Inclusive", stock: 45, sku: "SNY-WH1000XM5-BLK",
    barcode: "4548736132061", minimumStockAlert: 5, warehouse: "WH-BLR-01",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400", public_id: "products/sony-headphones" },
    images: [{ url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800", public_id: "products/sony-headphones-lg" }],
    shipping: { weight: 0.25, length: 20, width: 18, height: 9, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Driver Size","40mm"],["Frequency Response","4Hz–40kHz"],["Battery","30 hrs"],["Connectivity","Bluetooth 5.2"]]),
    variants: { colors: ["Black", "Silver"], sizes: [] },
    tags: ["headphones","sony","noise-canceling","wireless","audio"],
    seo: { metaTitle: "Sony WH-1000XM5 Headphones | HelloMem", metaDescription: "Buy Sony WH-1000XM5 noise-canceling headphones at best price.", keywords: ["sony headphones","noise canceling","wireless headphones"] },
    isFeatured: true, isActive: true, rating: 4.8, numReviews: 312,
  },
  {
    name: "Apple iPhone 15 Pro 128GB",
    slug: "apple-iphone-15-pro-128gb",
    description: "A17 Pro chip, 48MP camera system, titanium design, USB-C with USB 3 speeds and up to 23-hour video playback.",
    shortDescription: "Latest Apple iPhone with A17 Pro chip",
    category: catMap["electronics"], brand: "Apple", seller: sellerId,
    price: 129900, discountPrice: 124900, mrp: 134900, costPrice: 90000, gst: 18,
    taxType: "Inclusive", stock: 20, sku: "APPL-IP15PRO-128-TIT",
    barcode: "194253757023", minimumStockAlert: 3, warehouse: "WH-BLR-01",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400", public_id: "products/iphone15pro" },
    images: [{ url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800", public_id: "products/iphone15pro-lg" }],
    shipping: { weight: 0.19, length: 14.7, width: 7.1, height: 0.8, shippingCharge: 0, deliveryTime: "1-2 business days" },
    specifications: new Map([["Chip","A17 Pro"],["Display","6.1\" Super Retina XDR"],["Camera","48MP Main"],["Storage","128GB"]]),
    variants: { colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"], sizes: [] },
    tags: ["iphone","apple","smartphone","ios","5g"],
    seo: { metaTitle: "Apple iPhone 15 Pro 128GB | HelloMem", metaDescription: "Buy Apple iPhone 15 Pro at best price.", keywords: ["iphone 15 pro","apple smartphone"] },
    isFeatured: true, isActive: true, rating: 4.9, numReviews: 540,
  },
  {
    name: "Samsung 55\" 4K QLED Smart TV",
    slug: "samsung-55-4k-qled-smart-tv",
    description: "Quantum HDR, Real Game Enhancer+ with 120Hz refresh rate, Object Tracking Sound and smart home hub capabilities.",
    shortDescription: "55\" 4K QLED Smart TV with Quantum HDR",
    category: catMap["electronics"], brand: "Samsung", seller: sellerId,
    price: 74990, discountPrice: 64990, mrp: 84990, costPrice: 48000, gst: 18,
    taxType: "Inclusive", stock: 12, sku: "SAM-55QLED-2024",
    barcode: "8806094673500", minimumStockAlert: 2, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400", public_id: "products/samsung-tv" },
    images: [{ url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=800", public_id: "products/samsung-tv-lg" }],
    shipping: { weight: 15, length: 130, width: 80, height: 12, shippingCharge: 299, deliveryTime: "5-7 business days" },
    specifications: new Map([["Screen Size","55 inch"],["Resolution","4K UHD (3840x2160)"],["Refresh Rate","120Hz"],["HDR","Quantum HDR"]]),
    variants: { colors: ["Black"], sizes: ["43\"", "55\"", "65\"", "75\""] },
    tags: ["tv","samsung","qled","4k","smart-tv"],
    seo: { metaTitle: "Samsung 55\" QLED 4K TV | HelloMem", metaDescription: "Buy Samsung 55 inch QLED Smart TV at best price.", keywords: ["samsung tv","qled tv","4k tv"] },
    isFeatured: true, isActive: true, rating: 4.6, numReviews: 189,
  },
  {
    name: "Logitech MX Master 3S Wireless Mouse",
    slug: "logitech-mx-master-3s-wireless-mouse",
    description: "8000 DPI precision sensor, ultra-fast MagSpeed scrolling, ergonomic design, works on any surface including glass.",
    shortDescription: "Advanced wireless mouse for professionals",
    category: catMap["electronics"], brand: "Logitech", seller: sellerId,
    price: 9495, discountPrice: 7999, mrp: 9995, costPrice: 5000, gst: 18,
    taxType: "Inclusive", stock: 65, sku: "LOG-MXM3S-GRY",
    barcode: "5099206097926", minimumStockAlert: 10, warehouse: "WH-BLR-01",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400", public_id: "products/logitech-mouse" },
    images: [{ url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=800", public_id: "products/logitech-mouse-lg" }],
    shipping: { weight: 0.14, length: 12, width: 8, height: 4, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["DPI","200–8000"],["Battery","70 days"],["Connectivity","Bluetooth / USB receiver"],["Buttons","7"]]),
    variants: { colors: ["Graphite", "Pale Grey"], sizes: [] },
    tags: ["mouse","logitech","wireless","ergonomic","productivity"],
    seo: { metaTitle: "Logitech MX Master 3S Mouse | HelloMem", metaDescription: "Buy Logitech MX Master 3S wireless mouse.", keywords: ["logitech mouse","mx master","wireless mouse"] },
    isFeatured: false, isActive: true, rating: 4.7, numReviews: 423,
  },
  {
    name: "boAt Rockerz 450 Bluetooth Headphones",
    slug: "boat-rockerz-450-bluetooth-headphones",
    description: "15-hour playback, 40mm drivers, foldable design with voice assistant support and padded ear cushions.",
    shortDescription: "Affordable on-ear Bluetooth headphones",
    category: catMap["electronics"], brand: "boAt", seller: sellerId,
    price: 1499, discountPrice: 1299, mrp: 2990, costPrice: 700, gst: 18,
    taxType: "Inclusive", stock: 120, sku: "BOAT-R450-RED",
    barcode: "8906095100450", minimumStockAlert: 15, warehouse: "WH-BLR-01",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400", public_id: "products/boat-headphones" },
    images: [{ url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800", public_id: "products/boat-headphones-lg" }],
    shipping: { weight: 0.22, length: 18, width: 15, height: 8, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Driver","40mm"],["Battery","15 hrs"],["Bluetooth","5.0"],["Mic","Yes"]]),
    variants: { colors: ["Active Black", "Luscious Red", "Navy Blue"], sizes: [] },
    tags: ["headphones","boat","bluetooth","budget","music"],
    seo: { metaTitle: "boAt Rockerz 450 Headphones | HelloMem", metaDescription: "Buy boAt Rockerz 450 Bluetooth headphones.", keywords: ["boat headphones","bluetooth headphones","budget headphones"] },
    isFeatured: false, isActive: true, rating: 4.2, numReviews: 8920,
  },
  {
    name: "Anker 65W USB-C GaN Charger",
    slug: "anker-65w-usb-c-gan-charger",
    description: "Compact 65W GaN charger with 2 USB-C and 1 USB-A port, supports PPS and Power Delivery for laptops, phones and tablets.",
    shortDescription: "Compact 65W multi-port GaN charger",
    category: catMap["electronics"], brand: "Anker", seller: sellerId,
    price: 2999, discountPrice: 2499, mrp: 3499, costPrice: 1200, gst: 18,
    taxType: "Inclusive", stock: 80, sku: "ANK-65W-GAN-WHT",
    barcode: "0194644083885", minimumStockAlert: 10, warehouse: "WH-BLR-01",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400", public_id: "products/anker-charger" },
    images: [{ url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800", public_id: "products/anker-charger-lg" }],
    shipping: { weight: 0.09, length: 6, width: 4, height: 4, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Wattage","65W"],["Ports","2x USB-C, 1x USB-A"],["Technology","GaN II"],["Input","100-240V"]]),
    variants: { colors: ["White", "Black"], sizes: [] },
    tags: ["charger","anker","gan","usb-c","fast-charging"],
    seo: { metaTitle: "Anker 65W GaN Charger | HelloMem", metaDescription: "Buy Anker 65W GaN charger.", keywords: ["anker charger","gan charger","fast charger"] },
    isFeatured: false, isActive: true, rating: 4.5, numReviews: 672,
  },

  // ── Fashion (6) ──────────────────────────────────────────────────────────────
  {
    name: "Levi's 511 Slim Fit Jeans",
    slug: "levis-511-slim-fit-jeans-navy",
    description: "Classic slim-fit jeans made from stretch denim for all-day comfort. 98% cotton, 2% elastane.",
    shortDescription: "Classic slim-fit stretch denim jeans",
    category: catMap["fashion"], brand: "Levi's", seller: sellerId,
    price: 2999, discountPrice: 2399, mrp: 3999, costPrice: 1200, gst: 5,
    taxType: "Inclusive", stock: 85, sku: "LEVIS-511-NVY-32",
    barcode: "5401015017321", minimumStockAlert: 10, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400", public_id: "products/levis-jeans" },
    images: [{ url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800", public_id: "products/levis-jeans-lg" }],
    shipping: { weight: 0.5, length: 30, width: 20, height: 4, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Fit","Slim"],["Fabric","98% Cotton, 2% Elastane"],["Closure","Zip Fly"],["Rise","Mid Rise"]]),
    variants: { colors: ["Navy Blue", "Black", "Dark Grey"], sizes: ["28", "30", "32", "34", "36", "38"] },
    tags: ["jeans","levis","denim","slim-fit","men"],
    seo: { metaTitle: "Levi's 511 Slim Fit Jeans | HelloMem", metaDescription: "Buy Levi's 511 slim fit jeans online.", keywords: ["levis jeans","slim fit jeans","denim"] },
    isFeatured: true, isActive: true, rating: 4.5, numReviews: 2340,
  },
  {
    name: "Nike Air Max 270 Running Shoes",
    slug: "nike-air-max-270-running-shoes-white",
    description: "Max Air unit in the heel for all-day comfort. Engineered mesh upper for breathability and lightweight feel.",
    shortDescription: "Lightweight running shoes with Max Air cushioning",
    category: catMap["fashion"], brand: "Nike", seller: sellerId,
    price: 9995, discountPrice: 7999, mrp: 10995, costPrice: 4500, gst: 18,
    taxType: "Inclusive", stock: 55, sku: "NIKE-AM270-WHT-10",
    barcode: "0195244729390", minimumStockAlert: 8, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400", public_id: "products/nike-airmax" },
    images: [{ url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800", public_id: "products/nike-airmax-lg" }],
    shipping: { weight: 0.8, length: 32, width: 20, height: 14, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Upper","Engineered Mesh"],["Sole","Rubber"],["Closure","Lace-up"],["Technology","Max Air 270"]]),
    variants: { colors: ["White/Black", "Black/Red", "Grey/Blue"], sizes: ["6", "7", "8", "9", "10", "11", "12"] },
    tags: ["shoes","nike","running","airmax","sneakers"],
    seo: { metaTitle: "Nike Air Max 270 Shoes | HelloMem", metaDescription: "Buy Nike Air Max 270 running shoes.", keywords: ["nike shoes","air max","running shoes"] },
    isFeatured: true, isActive: true, rating: 4.6, numReviews: 1870,
  },
  {
    name: "Allen Solly Regular Fit Cotton Shirt",
    slug: "allen-solly-regular-fit-cotton-shirt-blue",
    description: "100% premium cotton shirt with spread collar, easy-iron finish. Perfect for office and casual wear.",
    shortDescription: "Premium cotton formal shirt for men",
    category: catMap["fashion"], brand: "Allen Solly", seller: sellerId,
    price: 1299, discountPrice: 999, mrp: 1699, costPrice: 450, gst: 5,
    taxType: "Inclusive", stock: 100, sku: "AS-RGF-CTN-BLU-M",
    barcode: "8906110120459", minimumStockAlert: 15, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400", public_id: "products/allen-solly-shirt" },
    images: [{ url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800", public_id: "products/allen-solly-shirt-lg" }],
    shipping: { weight: 0.3, length: 35, width: 25, height: 3, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Fabric","100% Cotton"],["Fit","Regular Fit"],["Collar","Spread Collar"],["Sleeve","Full Sleeve"]]),
    variants: { colors: ["Sky Blue", "White", "Light Grey", "Pale Yellow"], sizes: ["S", "M", "L", "XL", "XXL"] },
    tags: ["shirt","allen-solly","cotton","formal","men"],
    seo: { metaTitle: "Allen Solly Cotton Shirt | HelloMem", metaDescription: "Buy Allen Solly regular fit cotton shirt.", keywords: ["allen solly shirt","cotton shirt","formal shirt"] },
    isFeatured: false, isActive: true, rating: 4.3, numReviews: 945,
  },
  {
    name: "Puma Virat Kohli T-Shirt",
    slug: "puma-virat-kohli-dri-fit-tshirt-black",
    description: "dryCELL moisture-wicking technology, slim fit design, inspired by Virat Kohli's active collection.",
    shortDescription: "dri-fit sports T-shirt for men",
    category: catMap["fashion"], brand: "Puma", seller: sellerId,
    price: 899, discountPrice: 699, mrp: 1299, costPrice: 300, gst: 5,
    taxType: "Inclusive", stock: 150, sku: "PUMA-VK-DRYFIT-BLK-L",
    barcode: "4065449658706", minimumStockAlert: 20, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400", public_id: "products/puma-tshirt" },
    images: [{ url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800", public_id: "products/puma-tshirt-lg" }],
    shipping: { weight: 0.2, length: 30, width: 20, height: 2, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Fabric","polyester"],["Fit","Slim Fit"],["Technology","dryCELL"],["Sleeve","Half Sleeve"]]),
    variants: { colors: ["Black", "Navy", "Red", "White"], sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
    tags: ["tshirt","puma","sports","dri-fit","men"],
    seo: { metaTitle: "Puma dryCELL T-Shirt | HelloMem", metaDescription: "Buy Puma sports T-shirt.", keywords: ["puma tshirt","sports tshirt","dri fit"] },
    isFeatured: false, isActive: true, rating: 4.1, numReviews: 3210,
  },
  {
    name: "Fastrack Analog Watch for Women",
    slug: "fastrack-analog-watch-women-rose-gold",
    description: "Rose gold stainless steel case, mesh strap, mineral crystal glass and 3 ATM water resistance.",
    shortDescription: "Stylish rose gold analog watch for women",
    category: catMap["fashion"], brand: "Fastrack", seller: sellerId,
    price: 1995, discountPrice: 1599, mrp: 2495, costPrice: 700, gst: 12,
    taxType: "Inclusive", stock: 40, sku: "FT-ANA-WOM-RG-01",
    barcode: "8901179168007", minimumStockAlert: 5, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400", public_id: "products/fastrack-watch" },
    images: [{ url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800", public_id: "products/fastrack-watch-lg" }],
    shipping: { weight: 0.1, length: 10, width: 8, height: 5, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Case","Stainless Steel"],["Strap","Mesh"],["Water Resistance","3 ATM"],["Movement","Quartz"]]),
    variants: { colors: ["Rose Gold", "Silver", "Gold"] , sizes: [] },
    tags: ["watch","fastrack","women","analog","rose-gold"],
    seo: { metaTitle: "Fastrack Women's Watch | HelloMem", metaDescription: "Buy Fastrack analog watch for women.", keywords: ["fastrack watch","women watch","analog watch"] },
    isFeatured: false, isActive: true, rating: 4.0, numReviews: 567,
  },
  {
    name: "Campus Spirit Running Shoes Women",
    slug: "campus-spirit-running-shoes-women-pink",
    description: "Lightweight mesh upper, EVA midsole cushioning, anti-skid rubber outsole. Ideal for daily jogging.",
    shortDescription: "Lightweight women's running shoes",
    category: catMap["fashion"], brand: "Campus", seller: sellerId,
    price: 1499, discountPrice: 1099, mrp: 2199, costPrice: 550, gst: 18,
    taxType: "Inclusive", stock: 70, sku: "CAMP-SPRT-PNK-6",
    barcode: "8906124530068", minimumStockAlert: 10, warehouse: "WH-BLR-02",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400", public_id: "products/campus-shoes" },
    images: [{ url: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800", public_id: "products/campus-shoes-lg" }],
    shipping: { weight: 0.6, length: 30, width: 18, height: 12, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Upper","Mesh"],["Midsole","EVA"],["Outsole","Rubber"],["Closure","Lace-up"]]),
    variants: { colors: ["Pink/White", "Grey/Purple", "Black/Pink"], sizes: ["3", "4", "5", "6", "7", "8"] },
    tags: ["shoes","campus","women","running","sports"],
    seo: { metaTitle: "Campus Spirit Women Running Shoes | HelloMem", metaDescription: "Buy Campus Spirit women running shoes.", keywords: ["campus shoes","women shoes","running shoes"] },
    isFeatured: false, isActive: true, rating: 4.1, numReviews: 1230,
  },

  // ── Home & Kitchen (6) ───────────────────────────────────────────────────────
  {
    name: "Prestige Iris 750W Mixer Grinder",
    slug: "prestige-iris-750w-mixer-grinder",
    description: "750W motor, 3 stainless steel jars (1.5L, 1L, 0.4L), 3-speed control with incher, ISI certified.",
    shortDescription: "750W mixer grinder with 3 SS jars",
    category: catMap["home-kitchen"], brand: "Prestige", seller: sellerId,
    price: 2995, discountPrice: 2395, mrp: 3995, costPrice: 1200, gst: 18,
    taxType: "Inclusive", stock: 35, sku: "PRES-IRIS750-WHT",
    barcode: "8901962122014", minimumStockAlert: 5, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400", public_id: "products/prestige-mixer" },
    images: [{ url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800", public_id: "products/prestige-mixer-lg" }],
    shipping: { weight: 4.5, length: 38, width: 24, height: 28, shippingCharge: 99, deliveryTime: "4-6 business days" },
    specifications: new Map([["Power","750W"],["Jars","3"],["Speed","3 + Incher"],["Warranty","2 Years"]]),
    variants: { colors: ["White", "Red"], sizes: [] },
    tags: ["mixer","grinder","prestige","kitchen","appliance"],
    seo: { metaTitle: "Prestige Iris 750W Mixer Grinder | HelloMem", metaDescription: "Buy Prestige Iris mixer grinder.", keywords: ["prestige mixer","mixer grinder","kitchen appliance"] },
    isFeatured: false, isActive: true, rating: 4.3, numReviews: 1450,
  },
  {
    name: "Amazon Basics Non-Stick Cookware Set 5-Piece",
    slug: "amazon-basics-non-stick-cookware-set-5pc",
    description: "5-piece set includes 20cm fry pan, 24cm fry pan, 24cm kadhai, 24cm saucepan and a spatula. PFOA-free coating.",
    shortDescription: "5-piece non-stick PFOA-free cookware set",
    category: catMap["home-kitchen"], brand: "Amazon Basics", seller: sellerId,
    price: 1799, discountPrice: 1399, mrp: 2499, costPrice: 700, gst: 18,
    taxType: "Inclusive", stock: 50, sku: "AMZ-NONSTICK-5PC",
    barcode: "8906132500010", minimumStockAlert: 8, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400", public_id: "products/cookware-set" },
    images: [{ url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800", public_id: "products/cookware-set-lg" }],
    shipping: { weight: 3.2, length: 40, width: 30, height: 20, shippingCharge: 99, deliveryTime: "4-6 business days" },
    specifications: new Map([["Pieces","5"],["Coating","Non-stick PFOA-free"],["Compatible","Gas, Induction"],["Material","Aluminium"]]),
    variants: { colors: ["Black"], sizes: [] },
    tags: ["cookware","non-stick","kitchen","pan","kadhai"],
    seo: { metaTitle: "Non-Stick Cookware Set 5-Piece | HelloMem", metaDescription: "Buy non-stick cookware set.", keywords: ["cookware set","non stick pan","kitchen set"] },
    isFeatured: false, isActive: true, rating: 4.2, numReviews: 680,
  },
  {
    name: "Philips HD3165 Rice Cooker 1.8L",
    slug: "philips-hd3165-rice-cooker-1-8l",
    description: "1.8L capacity, keeps warm automatically, non-stick inner pot, 2-year warranty.",
    shortDescription: "1.8L electric rice cooker with keep-warm",
    category: catMap["home-kitchen"], brand: "Philips", seller: sellerId,
    price: 1895, discountPrice: 1599, mrp: 2295, costPrice: 800, gst: 18,
    taxType: "Inclusive", stock: 28, sku: "PHIL-HD3165-WHT",
    barcode: "8710103894193", minimumStockAlert: 4, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400", public_id: "products/rice-cooker" },
    images: [{ url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800", public_id: "products/rice-cooker-lg" }],
    shipping: { weight: 1.8, length: 28, width: 28, height: 20, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Capacity","1.8L"],["Power","500W"],["Keep Warm","Yes"],["Warranty","2 Years"]]),
    variants: { colors: ["White"], sizes: [] },
    tags: ["rice-cooker","philips","kitchen","electric","appliance"],
    seo: { metaTitle: "Philips 1.8L Rice Cooker | HelloMem", metaDescription: "Buy Philips HD3165 rice cooker.", keywords: ["philips rice cooker","electric rice cooker","1.8L cooker"] },
    isFeatured: false, isActive: true, rating: 4.4, numReviews: 890,
  },
  {
    name: "Solimo 100% Cotton Bath Towel Set (2 pcs)",
    slug: "solimo-100-cotton-bath-towel-set-2pc",
    description: "700 GSM ultra-soft towels, highly absorbent, quick dry, OEKO-TEX certified. Size: 75 x 150 cm.",
    shortDescription: "700 GSM ultra-soft cotton bath towels (set of 2)",
    category: catMap["home-kitchen"], brand: "Solimo", seller: sellerId,
    price: 799, discountPrice: 649, mrp: 999, costPrice: 300, gst: 5,
    taxType: "Inclusive", stock: 90, sku: "SOLIMO-TOWEL-2PC-NVY",
    barcode: "8906086780015", minimumStockAlert: 12, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1620626011761-996317702468?w=400", public_id: "products/bath-towel" },
    images: [{ url: "https://images.unsplash.com/photo-1620626011761-996317702468?w=800", public_id: "products/bath-towel-lg" }],
    shipping: { weight: 0.9, length: 35, width: 25, height: 8, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["GSM","700"],["Size","75 x 150 cm"],["Material","100% Cotton"],["Pack","2 Towels"]]),
    variants: { colors: ["Navy Blue", "White", "Grey", "Teal"], sizes: [] },
    tags: ["towel","bath","cotton","solimo","home"],
    seo: { metaTitle: "Solimo Cotton Bath Towel Set | HelloMem", metaDescription: "Buy Solimo 700 GSM cotton bath towels.", keywords: ["bath towel","cotton towel","700 gsm towel"] },
    isFeatured: false, isActive: true, rating: 4.3, numReviews: 2100,
  },
  {
    name: "Nilkamal Plastic Storage Cabinet 2-Door",
    slug: "nilkamal-plastic-storage-cabinet-2-door",
    description: "Weather-resistant PP plastic, 4 adjustable shelves, 2-door lockable cabinet. Weight capacity: 30kg per shelf.",
    shortDescription: "Durable 2-door plastic storage cabinet",
    category: catMap["home-kitchen"], brand: "Nilkamal", seller: sellerId,
    price: 3999, discountPrice: 3499, mrp: 5499, costPrice: 1800, gst: 18,
    taxType: "Inclusive", stock: 18, sku: "NILK-CAB2D-WHT",
    barcode: "8906120400150", minimumStockAlert: 3, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400", public_id: "products/nilkamal-cabinet" },
    images: [{ url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", public_id: "products/nilkamal-cabinet-lg" }],
    shipping: { weight: 12, length: 90, width: 50, height: 40, shippingCharge: 399, deliveryTime: "5-7 business days" },
    specifications: new Map([["Material","PP Plastic"],["Shelves","4 Adjustable"],["Doors","2 with Lock"],["Capacity","30kg/shelf"]]),
    variants: { colors: ["White", "Beige"], sizes: [] },
    tags: ["cabinet","storage","nilkamal","home","furniture"],
    seo: { metaTitle: "Nilkamal 2-Door Storage Cabinet | HelloMem", metaDescription: "Buy Nilkamal plastic storage cabinet.", keywords: ["nilkamal cabinet","storage cabinet","plastic cabinet"] },
    isFeatured: false, isActive: true, rating: 4.0, numReviews: 340,
  },
  {
    name: "Pigeon by Stovekraft Induction Cooktop 1800W",
    slug: "pigeon-stovekraft-induction-cooktop-1800w",
    description: "1800W induction cooktop with 7 preset menus, auto switch-off, crystal glass plate and feather-touch controls.",
    shortDescription: "1800W induction cooktop with 7 preset menus",
    category: catMap["home-kitchen"], brand: "Pigeon", seller: sellerId,
    price: 1799, discountPrice: 1499, mrp: 2499, costPrice: 750, gst: 18,
    taxType: "Inclusive", stock: 42, sku: "PIGEON-IND1800-BLK",
    barcode: "8906097720016", minimumStockAlert: 6, warehouse: "WH-BLR-03",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", public_id: "products/induction-cooktop" },
    images: [{ url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800", public_id: "products/induction-cooktop-lg" }],
    shipping: { weight: 1.4, length: 32, width: 28, height: 7, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Power","1800W"],["Presets","7"],["Panel","Crystal Glass"],["Warranty","1 Year"]]),
    variants: { colors: ["Black"], sizes: [] },
    tags: ["induction","cooktop","pigeon","kitchen","electric"],
    seo: { metaTitle: "Pigeon 1800W Induction Cooktop | HelloMem", metaDescription: "Buy Pigeon induction cooktop.", keywords: ["induction cooktop","pigeon cooktop","induction stove"] },
    isFeatured: false, isActive: true, rating: 4.2, numReviews: 3450,
  },

  // ── Sports & Fitness (6) ─────────────────────────────────────────────────────
  {
    name: "Boldfit Pro Gym Gloves",
    slug: "boldfit-pro-gym-gloves-black",
    description: "Anti-slip silicone grip, half-finger design, wrist wrap support, breathable lycra fabric. Unisex.",
    shortDescription: "Anti-slip gym gloves with wrist support",
    category: catMap["sports-fitness"], brand: "Boldfit", seller: sellerId,
    price: 499, discountPrice: 399, mrp: 799, costPrice: 150, gst: 18,
    taxType: "Inclusive", stock: 200, sku: "BOLD-GYMGLV-BLK-M",
    barcode: "8906134500113", minimumStockAlert: 25, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400", public_id: "products/gym-gloves" },
    images: [{ url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800", public_id: "products/gym-gloves-lg" }],
    shipping: { weight: 0.1, length: 18, width: 12, height: 3, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Material","Lycra + Silicone"],["Design","Half Finger"],["Wrist Wrap","Yes"],["Gender","Unisex"]]),
    variants: { colors: ["Black", "Black/Red", "Black/Blue"], sizes: ["S", "M", "L", "XL"] },
    tags: ["gym","gloves","boldfit","fitness","workout"],
    seo: { metaTitle: "Boldfit Pro Gym Gloves | HelloMem", metaDescription: "Buy Boldfit gym gloves with wrist support.", keywords: ["gym gloves","workout gloves","fitness gloves"] },
    isFeatured: false, isActive: true, rating: 4.2, numReviews: 5600,
  },
  {
    name: "Nivia Speedo Basketball",
    slug: "nivia-speedo-basketball-size-7",
    description: "Rubber basketball, official size 7, deep channel design for better grip. Suitable for outdoor courts.",
    shortDescription: "Rubber outdoor basketball size 7",
    category: catMap["sports-fitness"], brand: "Nivia", seller: sellerId,
    price: 699, discountPrice: 599, mrp: 899, costPrice: 280, gst: 18,
    taxType: "Inclusive", stock: 60, sku: "NIVIA-BBALL-SZ7",
    barcode: "8906049700072", minimumStockAlert: 8, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1546519638405-a9d1e7dcfc56?w=400", public_id: "products/basketball" },
    images: [{ url: "https://images.unsplash.com/photo-1546519638405-a9d1e7dcfc56?w=800", public_id: "products/basketball-lg" }],
    shipping: { weight: 0.6, length: 25, width: 25, height: 25, shippingCharge: 49, deliveryTime: "3-5 business days" },
    specifications: new Map([["Material","Rubber"],["Size","7 (Official)"],["Surface","Outdoor"],["Panels","8"]]),
    variants: { colors: ["Orange"], sizes: ["Size 5", "Size 6", "Size 7"] },
    tags: ["basketball","nivia","sports","outdoor","ball"],
    seo: { metaTitle: "Nivia Speedo Basketball Size 7 | HelloMem", metaDescription: "Buy Nivia Speedo basketball.", keywords: ["nivia basketball","basketball","sports ball"] },
    isFeatured: false, isActive: true, rating: 4.1, numReviews: 720,
  },
  {
    name: "Decathlon Corength 20kg Dumbbell Set",
    slug: "decathlon-corength-20kg-dumbbell-set",
    description: "Adjustable dumbbell set with cast iron plates and rubber grip handles. Total weight: 20kg (10kg x 2).",
    shortDescription: "20kg adjustable cast iron dumbbell set",
    category: catMap["sports-fitness"], brand: "Corength", seller: sellerId,
    price: 2499, discountPrice: 1999, mrp: 2999, costPrice: 1000, gst: 18,
    taxType: "Inclusive", stock: 25, sku: "DCT-DUMBBELL-20KG",
    barcode: "8906121400254", minimumStockAlert: 4, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400", public_id: "products/dumbbell-set" },
    images: [{ url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800", public_id: "products/dumbbell-set-lg" }],
    shipping: { weight: 20, length: 40, width: 30, height: 20, shippingCharge: 299, deliveryTime: "5-7 business days" },
    specifications: new Map([["Total Weight","20kg"],["Material","Cast Iron"],["Grip","Rubber"],["Adjustable","Yes"]]),
    variants: { colors: ["Black"], sizes: ["10kg Set", "20kg Set", "30kg Set"] },
    tags: ["dumbbell","weights","gym","fitness","strength"],
    seo: { metaTitle: "Corength 20kg Dumbbell Set | HelloMem", metaDescription: "Buy Corength adjustable dumbbell set.", keywords: ["dumbbell set","gym weights","home gym"] },
    isFeatured: true, isActive: true, rating: 4.5, numReviews: 380,
  },
  {
    name: "HealthSense Chef-Mate KS 33 Digital Kitchen Scale",
    slug: "healthsense-chef-mate-ks33-kitchen-scale",
    description: "5kg max capacity, 1g accuracy, tare function, LED display, stainless steel platform. 4 unit modes.",
    shortDescription: "5kg digital kitchen scale with tare function",
    category: catMap["sports-fitness"], brand: "HealthSense", seller: sellerId,
    price: 699, discountPrice: 549, mrp: 999, costPrice: 250, gst: 18,
    taxType: "Inclusive", stock: 110, sku: "HS-KS33-WHT",
    barcode: "8906065670033", minimumStockAlert: 15, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400", public_id: "products/kitchen-scale" },
    images: [{ url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800", public_id: "products/kitchen-scale-lg" }],
    shipping: { weight: 0.4, length: 20, width: 15, height: 5, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Capacity","5kg"],["Accuracy","1g"],["Platform","Stainless Steel"],["Units","kg/g/lb/oz"]]),
    variants: { colors: ["White", "Black"], sizes: [] },
    tags: ["kitchen-scale","healthsense","weighing","fitness","diet"],
    seo: { metaTitle: "HealthSense Digital Kitchen Scale | HelloMem", metaDescription: "Buy HealthSense digital kitchen scale.", keywords: ["kitchen scale","digital scale","weighing scale"] },
    isFeatured: false, isActive: true, rating: 4.3, numReviews: 2890,
  },
  {
    name: "Strauss Yoga Mat 6mm Anti-Skid",
    slug: "strauss-yoga-mat-6mm-anti-skid-purple",
    description: "6mm thick, TPE material, anti-skid surface on both sides, includes carrying strap. 183x61cm.",
    shortDescription: "6mm TPE anti-skid yoga mat with strap",
    category: catMap["sports-fitness"], brand: "Strauss", seller: sellerId,
    price: 799, discountPrice: 649, mrp: 1299, costPrice: 280, gst: 18,
    taxType: "Inclusive", stock: 95, sku: "STRSS-YM6MM-PUR",
    barcode: "8906050100062", minimumStockAlert: 12, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400", public_id: "products/yoga-mat" },
    images: [{ url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800", public_id: "products/yoga-mat-lg" }],
    shipping: { weight: 0.9, length: 65, width: 15, height: 15, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Thickness","6mm"],["Material","TPE"],["Size","183x61cm"],["Includes","Carrying Strap"]]),
    variants: { colors: ["Purple", "Blue", "Green", "Grey"], sizes: [] },
    tags: ["yoga-mat","strauss","yoga","fitness","exercise"],
    seo: { metaTitle: "Strauss 6mm Yoga Mat | HelloMem", metaDescription: "Buy Strauss anti-skid yoga mat.", keywords: ["yoga mat","strauss yoga mat","exercise mat"] },
    isFeatured: false, isActive: true, rating: 4.4, numReviews: 6700,
  },
  {
    name: "Boldfit Skipping Rope with Counter",
    slug: "boldfit-skipping-rope-with-counter",
    description: "Ball-bearing mechanism for tangle-free spinning, digital counter, adjustable PVC rope, foam handles.",
    shortDescription: "Adjustable skipping rope with digital counter",
    category: catMap["sports-fitness"], brand: "Boldfit", seller: sellerId,
    price: 349, discountPrice: 299, mrp: 599, costPrice: 100, gst: 18,
    taxType: "Inclusive", stock: 180, sku: "BOLD-SKIP-BLK",
    barcode: "8906134500120", minimumStockAlert: 20, warehouse: "WH-BLR-04",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=400", public_id: "products/skipping-rope" },
    images: [{ url: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800", public_id: "products/skipping-rope-lg" }],
    shipping: { weight: 0.15, length: 20, width: 15, height: 5, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Rope","PVC Adjustable"],["Handle","Foam Grip"],["Counter","Digital"],["Bearing","Ball Bearing"]]),
    variants: { colors: ["Black", "Red", "Blue"], sizes: [] },
    tags: ["skipping-rope","boldfit","cardio","fitness","jump"],
    seo: { metaTitle: "Boldfit Skipping Rope with Counter | HelloMem", metaDescription: "Buy Boldfit skipping rope with digital counter.", keywords: ["skipping rope","jump rope","cardio rope"] },
    isFeatured: false, isActive: true, rating: 4.3, numReviews: 9200,
  },

  // ── Books (6) ────────────────────────────────────────────────────────────────
  {
    name: "Atomic Habits by James Clear",
    slug: "atomic-habits-james-clear-paperback",
    description: "An easy and proven way to build good habits and break bad ones. Over 15 million copies sold worldwide.",
    shortDescription: "International bestseller on building good habits",
    category: catMap["books"], brand: "Penguin Random House", seller: sellerId,
    price: 499, discountPrice: 349, mrp: 599, costPrice: 120, gst: 0,
    taxType: "Inclusive", stock: 200, sku: "BK-ATOMICHAB-PBK",
    barcode: "9780735211292", minimumStockAlert: 20, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400", public_id: "products/atomic-habits" },
    images: [{ url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800", public_id: "products/atomic-habits-lg" }],
    shipping: { weight: 0.3, length: 21, width: 14, height: 2, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","James Clear"],["Pages","320"],["Language","English"],["ISBN","9780735211292"]]),
    variants: { colors: [], sizes: ["Paperback", "Hardcover", "Kindle"] },
    tags: ["books","self-help","habits","productivity","james-clear"],
    seo: { metaTitle: "Atomic Habits by James Clear | HelloMem", metaDescription: "Buy Atomic Habits paperback.", keywords: ["atomic habits","james clear","self help book","habit book"] },
    isFeatured: true, isActive: true, rating: 4.9, numReviews: 12000,
  },
  {
    name: "Rich Dad Poor Dad by Robert T. Kiyosaki",
    slug: "rich-dad-poor-dad-kiyosaki-paperback",
    description: "The #1 personal finance book of all time. What the rich teach their kids about money that the poor and middle class do not.",
    shortDescription: "#1 personal finance bestseller",
    category: catMap["books"], brand: "Manjul Publishing", seller: sellerId,
    price: 299, discountPrice: 199, mrp: 350, costPrice: 80, gst: 0,
    taxType: "Inclusive", stock: 175, sku: "BK-RICHDAD-PBK",
    barcode: "9781612680194", minimumStockAlert: 20, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400", public_id: "products/rich-dad" },
    images: [{ url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800", public_id: "products/rich-dad-lg" }],
    shipping: { weight: 0.25, length: 20, width: 13, height: 1.5, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","Robert T. Kiyosaki"],["Pages","286"],["Language","English"],["ISBN","9781612680194"]]),
    variants: { colors: [], sizes: ["Paperback", "Hardcover"] },
    tags: ["books","finance","money","kiyosaki","investing"],
    seo: { metaTitle: "Rich Dad Poor Dad | HelloMem", metaDescription: "Buy Rich Dad Poor Dad book.", keywords: ["rich dad poor dad","personal finance book","kiyosaki"] },
    isFeatured: true, isActive: true, rating: 4.7, numReviews: 8900,
  },
  {
    name: "The Psychology of Money by Morgan Housel",
    slug: "psychology-of-money-morgan-housel-paperback",
    description: "Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the way people think about money.",
    shortDescription: "Timeless lessons on wealth and happiness",
    category: catMap["books"], brand: "Jaico Publishing", seller: sellerId,
    price: 399, discountPrice: 299, mrp: 499, costPrice: 100, gst: 0,
    taxType: "Inclusive", stock: 160, sku: "BK-PSYCHMONEY-PBK",
    barcode: "9780857197689", minimumStockAlert: 20, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400", public_id: "products/psych-money" },
    images: [{ url: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800", public_id: "products/psych-money-lg" }],
    shipping: { weight: 0.28, length: 21, width: 14, height: 1.8, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","Morgan Housel"],["Pages","256"],["Language","English"],["ISBN","9780857197689"]]),
    variants: { colors: [], sizes: ["Paperback", "Hardcover"] },
    tags: ["books","finance","psychology","money","morgan-housel"],
    seo: { metaTitle: "The Psychology of Money | HelloMem", metaDescription: "Buy The Psychology of Money book.", keywords: ["psychology of money","morgan housel","finance book"] },
    isFeatured: false, isActive: true, rating: 4.8, numReviews: 6500,
  },
  {
    name: "Wings of Fire by APJ Abdul Kalam",
    slug: "wings-of-fire-apj-abdul-kalam-paperback",
    description: "Autobiography of one of India's most beloved presidents and scientists. Inspiring story of a boy from Rameswaram.",
    shortDescription: "Autobiography of Dr. APJ Abdul Kalam",
    category: catMap["books"], brand: "Universities Press", seller: sellerId,
    price: 175, discountPrice: 149, mrp: 225, costPrice: 55, gst: 0,
    taxType: "Inclusive", stock: 230, sku: "BK-WINGSFIRE-PBK",
    barcode: "9788173711466", minimumStockAlert: 25, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1476275466078-4cdc09f05b93?w=400", public_id: "products/wings-of-fire" },
    images: [{ url: "https://images.unsplash.com/photo-1476275466078-4cdc09f05b93?w=800", public_id: "products/wings-of-fire-lg" }],
    shipping: { weight: 0.2, length: 19, width: 13, height: 1.2, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","APJ Abdul Kalam"],["Pages","196"],["Language","English"],["ISBN","9788173711466"]]),
    variants: { colors: [], sizes: ["Paperback"] },
    tags: ["books","biography","kalam","india","inspiration"],
    seo: { metaTitle: "Wings of Fire by APJ Abdul Kalam | HelloMem", metaDescription: "Buy Wings of Fire autobiography.", keywords: ["wings of fire","apj kalam","biography"] },
    isFeatured: false, isActive: true, rating: 4.8, numReviews: 5400,
  },
  {
    name: "Let Us C by Yashavant Kanetkar",
    slug: "let-us-c-yashavant-kanetkar-17th-edition",
    description: "17th edition of the classic C programming book. Covers fundamentals to advanced topics with exercises.",
    shortDescription: "Classic C programming textbook - 17th edition",
    category: catMap["books"], brand: "BPB Publications", seller: sellerId,
    price: 499, discountPrice: 399, mrp: 595, costPrice: 150, gst: 0,
    taxType: "Inclusive", stock: 140, sku: "BK-LETUSC-17ED",
    barcode: "9789388511018", minimumStockAlert: 15, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400", public_id: "products/let-us-c" },
    images: [{ url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800", public_id: "products/let-us-c-lg" }],
    shipping: { weight: 0.65, length: 24, width: 17, height: 3, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","Yashavant Kanetkar"],["Edition","17th"],["Pages","578"],["Language","English"]]),
    variants: { colors: [], sizes: ["Paperback"] },
    tags: ["books","programming","c-language","education","textbook"],
    seo: { metaTitle: "Let Us C - 17th Edition | HelloMem", metaDescription: "Buy Let Us C programming book.", keywords: ["let us c","c programming","kanetkar","programming book"] },
    isFeatured: false, isActive: true, rating: 4.5, numReviews: 3100,
  },
  {
    name: "The Alchemist by Paulo Coelho",
    slug: "the-alchemist-paulo-coelho-paperback",
    description: "A mystical story of Santiago, an Andalusian shepherd boy, who yearns to travel in search of a worldly treasure.",
    shortDescription: "World's best-selling philosophical novel",
    category: catMap["books"], brand: "HarperCollins", seller: sellerId,
    price: 299, discountPrice: 239, mrp: 399, costPrice: 90, gst: 0,
    taxType: "Inclusive", stock: 210, sku: "BK-ALCHEMIST-PBK",
    barcode: "9780062315007", minimumStockAlert: 20, warehouse: "WH-BLR-05",
    stockStatus: "In Stock",
    thumbnail: { url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400", public_id: "products/the-alchemist" },
    images: [{ url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800", public_id: "products/the-alchemist-lg" }],
    shipping: { weight: 0.22, length: 20, width: 13, height: 1.5, shippingCharge: 0, deliveryTime: "3-5 business days" },
    specifications: new Map([["Author","Paulo Coelho"],["Pages","197"],["Language","English"],["ISBN","9780062315007"]]),
    variants: { colors: [], sizes: ["Paperback", "Hardcover"] },
    tags: ["books","fiction","novel","philosophy","coelho"],
    seo: { metaTitle: "The Alchemist by Paulo Coelho | HelloMem", metaDescription: "Buy The Alchemist novel.", keywords: ["the alchemist","paulo coelho","philosophical novel"] },
    isFeatured: true, isActive: true, rating: 4.8, numReviews: 14000,
  },
];


// ─── Main Seed Function ────────────────────────────────────────────────────────
const seed = async () => {
  await connectDB();

  try {
    console.log("\n🌱  Starting seed...\n");

    // 1. Upsert categories
    console.log("📂  Seeding categories...");
    const catMap = {};
    for (const cat of CATEGORIES) {
      // Try to find by slug first, then by name (handles inconsistent existing data)
      let existing = await Category.findOne({ slug: cat.slug });
      if (!existing) existing = await Category.findOne({ name: cat.name });
      if (existing) {
        catMap[cat.slug] = existing._id;
        console.log(`   ↩  Reusing: ${cat.name} (${existing._id})`);
      } else {
        const created = await Category.create({ ...cat, isActive: true, isFeatured: false, displayOrder: 0 });
        catMap[cat.slug] = created._id;
        console.log(`   ✔  Created: ${cat.name} (${created._id})`);
      }
    }

    // 2. Upsert demo seller
    console.log("\n🧑‍💼  Seeding seller...");
    let seller = await Seller.findOne({ email: SELLER.email });
    if (!seller) {
      seller = await Seller.create({ ...SELLER });
      console.log(`   ✔  Created seller: ${seller.email}`);
    } else {
      console.log(`   ↩  Reusing existing seller: ${seller.email}`);
    }

    // 3. Insert products (skip duplicates by sku)
    console.log("\n📦  Seeding products...");
    const products = buildProducts(catMap, seller._id);
    let created = 0, skipped = 0;

    for (const p of products) {
      const exists = await Product.findOne({ sku: p.sku });
      if (exists) {
        console.log(`   ↩  Skipped (already exists): ${p.name}`);
        skipped++;
      } else {
        await Product.create(p);
        console.log(`   ✔  Added: ${p.name}`);
        created++;
      }
    }

    console.log(`\n✅  Seed complete!`);
    console.log(`   Categories : ${Object.keys(catMap).length}`);
    console.log(`   Products   : ${created} created, ${skipped} skipped`);
  } catch (err) {
    console.error("\n❌  Seed failed:", err.message);
    console.error(err);
  } finally {
    await mongoose.disconnect();
    console.log("\n🔌  MongoDB disconnected.\n");
  }
};

seed();
